# Generated by Django 4.0.4 on 2022-05-17 12:00

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('department', '0001_initial'),
    ]

    operations = [
        migrations.AddField(
            model_name='general',
            name='content',
            field=models.TextField(blank=True, verbose_name='Контент'),
        ),
    ]
